FROM python:3.12-slim

WORKDIR /app

# сначала зависимости (кэширование слоёв)
COPY requirements.txt .
RUN pip install -r requirements.txt

# потом код
COPY . .

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]