FROM python:3.12-slim

WORKDIR /app

# сначала зависимости (кэширование слоёв)
COPY requirements.txt .
RUN pip install -r requirements.txt

# потом код
COPY . .

CMD ["fastmcp", "run", "mcp_server.py", "--transport", "sse", "--port", "8001"]
